services:
  - type: web
    name: ucchristus-backend
    env: python
    runtime: python-3.11
    plan: free

    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput

    postDeployCommand: >
      python manage.py migrate --noinput &&
      python manage.py seed_db --force

    startCommand: >
      sh -c "python manage.py migrate --noinput &&
            python manage.py seed_db --force &&
            gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"


    healthCheckPath: /health/

    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: ucchristus-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://iic-3144-ucchristus-estadia-fronten.vercel.app"

databases:
  - name: ucchristus-db
    databaseName: ucchristus_db
    user: ucchristus_user
    plan: free
